#!/usr/bin/env bash
# kit-gates.sh — KIT-OWNED. DO NOT EDIT THIS FILE.
#
# Vendored from the standards repo and verified by checksum against
# `.kit/MANIFEST`. Local edits make `./verify` go red on purpose: the whole
# point of vendoring is that this file is byte-identical everywhere, so a repo
# that customises it has silently opted out of the policy it claims to carry.
#
#   update:  python3 <kit>/kit_sync.py <repo>          (writes files + MANIFEST)
#   check:   python3 <kit>/kit_sync.py <repo> --check  (hash compare, no writes)
#
# Why vendored rather than sourced from one shared copy: CI has no checkout of
# the standards repo, and a gate that cannot run in CI is not a gate. Why
# checksummed rather than trusted: before this, `leak_gate` had drifted into
# TEN distinct implementations across the fleet, nine of them missing the
# Windows identity pattern, while every one of those repos declared a
# kit_version (2026-08-18). A copy can lie; a hash cannot.
#
# Project-owned code lives in ./verify, which sources this file. Put project
# test commands THERE, never here.

record() { # record <target> <exit_code>
  local git_hash; git_hash=$(git rev-parse --short HEAD 2>/dev/null || echo "no-git")
  printf '{"target":"%s","exit":%d,"git":"%s","ts":"%s"}\n' \
    "$1" "$2" "$git_hash" "$(date -u +%FT%TZ)" > "$HARNESS_DIR/last-verify.json"
  rm -f "$HARNESS_DIR/dirty"
  return "$2"
}

# --- leak gate (kit-core — DO NOT delete; keep self-contained) --------------
# No machine-absolute home paths in tracked files: they bake the local username
# and directory layout into the repo — and into any public remote. Use a
# ~/-relative path or an env var instead. Prose placeholders (/Users/<user>/,
# /home/$USER/) are docs ABOUT the pattern, not leaks, and are allowed.
# NB: git grep uses POSIX ERE — no \s, no \d. (A \s here silently matches
# NOTHING; that is how the fleet scanner once shipped blind. Keep it ERE-safe.)
# --untracked is load-bearing: git grep defaults to TRACKED files only, so a
# brand-new file is invisible to the gate until it is staged. Running verify
# before `git add` then passes, and CI fails after the commit lands — which is
# exactly how the first version of this gate shipped its own leak. Untracked
# but not-gitignored == about to be committed, so scan it.
# KNOWN FALSE POSITIVES (substack2pdf, 2026-08-18): the pattern is a PATH shape,
# not a hostname check, so a URL whose path happens to read /home/<segment>/ or
# /Users/<segment>/ trips it — Substack reader URLs are the found case. That is
# correct conservative behaviour, not a bug: the gate cannot tell a URL path
# from a filesystem path without knowing intent. Prefer REWORDING the prose to
# allowlisting the file (two repos have now chosen reword), because an
# allowlist entry blinds the gate to that whole file forever, while a reword
# costs one sentence.
# Allowlist: security docs legitimately CONTAIN the patterns (they are docs
# ABOUT leaks). `.leakcheck-allow` lists exempt paths/globs, one per line
# (# comments ok). Exemptions are commits too — justify sensitive ones in
# DECISIONS.md. The scanner and the allowlist file are always exempt.
leak_gate() {
  # A foreign process may be probing this repo right now. `kit/currency.py`
  # proves the gate FIRES by planting identity paths in `.kit-currency-plant-*`
  # inside this working tree and running this very script — so a concurrent
  # `./verify fast` of our own reads the other run's plant and goes red on a
  # file that no longer exists by the time anyone looks (mind-lathe, 2026-08-18;
  # a retrofit ends by forcing a verify, which is exactly when the probe runs).
  # Plants are therefore invisible EXCEPT to the probe that owns the run, which
  # names its file in KIT_LEAK_PLANT. Not a weakening: the excluded name is a
  # fixed dot-prefixed pattern no project file uses, and the owning probe still
  # sees it.
  local hits excludes=(':(exclude)*leak_scan.py' ':(exclude).leakcheck-allow')
  if [ -n "${KIT_LEAK_PLANT:-}" ]; then
    # Owned run: every OTHER session's plant is still excluded, ours is not.
    local other
    for other in .kit-currency-plant-*; do
      [ "$other" = "$KIT_LEAK_PLANT" ] || [ ! -e "$other" ] || excludes+=(":(exclude)$other")
    done
  else
    excludes+=(':(exclude).kit-currency-plant-*')
  fi
  if [ -f .leakcheck-allow ]; then
    local line
    while IFS= read -r line; do
      line="${line%%#*}"; line="${line#"${line%%[![:space:]]*}"}"  # strip comment + lead ws
      line="${line%"${line##*[![:space:]]}"}"                       # strip trailing ws
      [ -n "$line" ] && excludes+=(":(exclude)$line")
    done < .leakcheck-allow
  fi
  # Two identity shapes: POSIX `/Users|home/<name>/` and the Windows drive
  # form. The `\\+` quantifier (not a fixed `\\`) is load-bearing: it matches
  # the raw single-backslash form AND the doubled-backslash escaped form a
  # Windows agent writes into JSON. Written without a literal example on
  # purpose — this gate greps itself, and a literal here matches itself
  # (spectral-morph-001 found exactly that trap). Kept byte-identical to
  # autonomous/verify and governor/leak_scan.py: three detectors, one policy.
  hits=$(git grep --untracked -nIE '/(Users|home)/[^/]+/|[A-Za-z]:\\+Users\\+[^\\]' -- . "${excludes[@]}" 2>/dev/null \
         | grep -vE '/(Users|home)/[<$@{%]|[A-Za-z]:\\+Users\\+[<$@{%]' || true)
  [ -z "$hits" ] && return 0
  echo "verify: LEAK — machine-absolute path in a tracked file (use ~/ instead):" >&2
  echo "$hits" | sed 's/^/    /' >&2
  return 1
}

# --- kit integrity (kit-core) ----------------------------------------------
# Every vendored file must still hash to what MANIFEST says. This catches the
# accidental case — a well-meaning local edit to a machine-owned file — which
# is the case that actually happens. It is NOT tamper-proof: this check lives
# inside a file it checks, so deleting the check deletes the check. The
# authoritative comparison is external (`kit_sync.py --check` against the
# standards repo, and `currency.py`, which reads MANIFEST rather than probing
# behaviour). Claim what it does: drift detection, not tamper resistance.
kit_integrity() {
  local man=".kit/MANIFEST" bad=0 line want got f
  [ -f "$man" ] || { echo "verify: no .kit/MANIFEST — run kit_sync.py" >&2; return 1; }
  while IFS= read -r line; do
    case "$line" in ''|\#*|kit_version:*) continue ;; esac
    want="${line%% *}"; f="${line##* }"
    [ -f ".kit/$f" ] || { echo "verify: .kit/$f missing (MANIFEST lists it)" >&2; bad=1; continue; }
    got=$(shasum -a 256 ".kit/$f" 2>/dev/null | cut -d' ' -f1)
    [ "$got" = "$want" ] || { echo "verify: .kit/$f was edited — it is kit-owned. Re-run kit_sync.py" >&2; bad=1; }
  done < "$man"
  return "$bad"
}
